# Generated by Django 4.2.4 on 2023-11-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_telephone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='school_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
