# Generated by Django 4.2.4 on 2023-11-18 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0002_schoolprofile_school_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
