# Generated by Django 4.2.4 on 2023-11-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0003_schoolprofile_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
