# Generated by Django 4.2.4 on 2023-11-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_profile', '0004_schoolprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
