# Generated by Django 4.2.4 on 2023-11-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='current_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
